spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true